// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_start_web_chat from "./routes/api/start-web-chat.ts";
import * as $index from "./routes/index.tsx";
import * as $buttons from "./islands/buttons.tsx";
import * as $chat_channel from "./islands/chat-channel.tsx";
import * as $chat_welcome from "./islands/chat-welcome.tsx";
import * as $chat from "./islands/chat.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/start-web-chat.ts": $api_start_web_chat,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/buttons.tsx": $buttons,
    "./islands/chat-channel.tsx": $chat_channel,
    "./islands/chat-welcome.tsx": $chat_welcome,
    "./islands/chat.tsx": $chat,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
